config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"
  resources :centers, only: [:new, :create] do
    resources :matrices, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/behavioral_marker.rb
# == Schema Information
#
# Table name: behavioral_markers
#
#  id            :bigint           not null, primary key
#  marker        :string
#  competency_id :bigint           not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class BehavioralMarker < ApplicationRecord
  belongs_to :competency
end

app/models/center.rb
# == Schema Information
#
# Table name: centers
#
#  id                  :bigint           not null, primary key
#  name                :string
#  competency_model_id :bigint           not null
#  storyline_id        :bigint           not null
#
class Center < ApplicationRecord
  belongs_to :competency_model
  belongs_to :storyline
  has_one :matrix
end

app/models/competency.rb
# == Schema Information
#
# Table name: competencies
#
#  id                  :bigint           not null, primary key
#  name                :string
#  competency_model_id :bigint           not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
class Competency < ApplicationRecord
  belongs_to :competency_model
  has_many :behavioral_markers, dependent: :destroy
end

app/models/competency_model.rb
# == Schema Information
#
# Table name: competency_models
#
#  id   :bigint           not null, primary key
#  name :string
#
class CompetencyModel < ApplicationRecord
  has_many :centers
  has_many :competencies, dependent: :destroy

end

app/models/competency_slot.rb
class CompetencySlot < ApplicationRecord
  belongs_to :exercise_slots
end

app/models/exercise.rb
# == Schema Information
#
# Table name: exercises
#
#  id           :bigint           not null, primary key
#  name         :string
#  storyline_id :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Exercise < ApplicationRecord
  belongs_to :storyline
end

app/models/exercise_slot.rb
class ExerciseSlot < ApplicationRecord
  has_many :competency_slots
  belongs_to :matrix
end

app/models/matrix.rb
class Matrix < ApplicationRecord
  belongs_to :center
  has_many :exercise_slots
end

app/models/new_matrix_form.rb
class NewMatrixForm
  include ActiveModel::Model

  attr_reader :ex_slots, :comps_per_exercise

  validate :slots_cannot_have_the_same_exercise
  validate :competencies_cannot_be_repeated_in_an_exercise


  def initialize(ex_slots=4, comps_per_exercise=4)
    @ex_slots = ex_slots
    @comps_per_exercise = comps_per_exercise
    create_ex_slots_and_competencies
    super()
  end

  def build_from(form_params)
    form_params.each_pair do |key, value|
      if key.to_s.match?(/exercise_slot_/) && self.respond_to?("#{key}".to_sym)
        self.instance_variable_set("@#{key}".to_sym, value)
      elsif value.is_a? ActionController::Parameters
        comp_group = value
        comp_group.each_pair do |key, value|
           self.instance_variable_set("@#{key}".to_sym, value)
        end
      end
    end
    # add the right form values to the right ex_slots and competencies.
    # this method couples the view to the form
  end

  def save
    return false if invalid?
    # TODO
    # Actually build freaking records
    # Create a matrix!
    matrix = Matrix.create(center: Center.find(params[:id]))
    self.exercise_slots.each do |ex_id|
      exercise = ExerciseSlot.create(matrix: matrix)
      self.competencies_for_ex(ex_id).each do |comp_id|
        CompetencySlot.create(exercise_slot: exercise)
      end
    end

  def exercise_slots
  end

  def competencies_for_ex(ex_number)

  end

  def slots_cannot_have_the_same_exercise
    errors.add(:ex_slots, "exercises cannot be repeated" ) if ex_slot_values != ex_slot_values.uniq
    errors.add(:ex_slots, "you must select at least one exercise" ) if ex_slot_values.empty?
  end

  private

  def create_ex_slots_and_competencies
    @ex_slots.times do |n|
      singleton_class.class_eval { attr_accessor "exercise_slot_#{n + 1}" }
      @comps_per_exercise.times do |i|
        singleton_class.class_eval { attr_accessor "ex_slot_#{n + 1}_comp_#{i + 1}" }
      end
    end
  end

  def ex_slot_values
    instance_variables.select { |attr| attr.match?(/@exercise_slot_/ )}
                                       .map { |var| self.instance_variable_get(var) }
  end


  def competencies_cannot_be_repeated_in_an_exercise
    @ex_slots.times do |n|
      comps_in_exercise = []
      @comps_per_exercise.times do |i|
        comps_in_exercise << instance_variable_get("@ex_slot_#{n + 1}_comp_#{i + 1}")
      end

      case
      when comps_in_exercise.compact.empty?
        errors.add("ex_slot_#{n + 1}".to_sym, "You must select at least one competency for this exercise")
      when comps_in_exercise != comps_in_exercise.uniq && comps_in_exercise.length > 1
        errors.add("ex_slot_#{n + 1}".to_sym, "competencies cannot be repeated in the same exercise")
      end
    end
  end

end

app/models/storyline.rb
# == Schema Information
#
# Table name: storylines
#
#  id   :bigint           not null, primary key
#  name :string
#
class Storyline < ApplicationRecord
  has_many :centers
  has_many :exercises, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
  def new
    @center = Center.new
  end

  def create
    @center = Center.new(center_params)
    if @center.save
      redirect_to new_center_matrix_path(@center)
    else
      flash[:notice] = 'something went wrong'
      render :new
    end
  end


  private


  def center_params
    values = params.require(:center).permit(:storyline, :competency_model)
    {
      storyline: Storyline.find(values[:storyline]),
      competency_model: CompetencyModel.find(values[:competency_model])
     }
  end
end

app/controllers/matrices_controller.rb
class MatricesController < ApplicationController
  def new
    @center = Center.find(params[:center_id])
    @exercises = @center.storyline.exercises
    @competencies = @center.competency_model.competencies
    @new_matrix_form = NewMatrixForm.new(1,2)
  end

  def create
    @new_matrix_form = NewMatrixForm.new(1,2)
    @new_matrix_form.build_from(matrix_form_params)
    if @new_matrix_form.save
      redirect_to root_path
    else
      render :new
    end
  end

  def matrix_form_params
    params.require(:new_matrix_form).permit!
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/centers/new.html.erb
<h1 class="mt-5">Create a new center</h1>
<%= simple_form_for @center, html: { class: "w-50" } do |f| %>
  <%= f.input :storyline, collection: Storyline.all, label_method: :name, input_html: { required: true } %>
  <%= f.input :competency_model, collection: CompetencyModel.all, label_method: :name, input_html: { required: true }%>
  <%= f.submit :create, class: "btn btn-primary w-100" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roleplaywriter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/matrices/create.html.erb
<h1>Matrices#create</h1>
<p>Find me in app/views/matrices/create.html.erb</p>

app/views/matrices/new.html.erb
<h1> Create a New Matrix </h1>

<!-- So this is a crazy form that takes -->
<!-- 4 Exercises -->
<%= simple_form_for @new_matrix_form, url: center_matrices_path(@center) do |f| %>
  <% @new_matrix_form.ex_slots.times do |n| %>
    <%= f.input "exercise_slot_#{n + 1}".to_sym, collection: @exercises %>
    <% @new_matrix_form.comps_per_exercise.times do |i| %>
    <%= f.simple_fields_for "comp_slots_ex_#{i + 1}".to_sym do |f| %>
      <%= f.input "ex_slot_#{n + 1}_comp_#{i + 1}", collection: @competencies %>
    <% end %>
      <hr>
    <% end %>
  <% end %>
  <%=  f.submit "create matrix", class: "btn btn-primary w-100" %>
<% end %>
<!-- For each exercise -->
<!-- 4 competencies -->
<!-- So I need some sort of form group -->
<!-- And on creation, add everything to the right place -->

app/views/pages/home.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">RolePlay Writer 🗒</h1>
    <p class="lead">The tool I wished I had in 2016.</p>
    <hr class="my-4">
    <%= link_to 'Create New Center', new_center_path, class: 'btn btn-primary' %>
  </div>
</div>